"""Add agent_memories table

Revision ID: 81757c83f1fe
Revises: c3d4e5f6a7b8
Create Date: 2026-04-13 18:44:43.063688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81757c83f1fe'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=True),
    sa.Column('related_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_memories_user_importance', 'agent_memories', ['user_id', 'importance'], unique=False)
    op.create_index('idx_agent_memories_user_round', 'agent_memories', ['user_id', 'round_num'], unique=False)
    op.create_index('idx_agent_memories_user_type', 'agent_memories', ['user_id', 'memory_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_agent_memories_user_type', table_name='agent_memories')
    op.drop_index('idx_agent_memories_user_round', table_name='agent_memories')
    op.drop_index('idx_agent_memories_user_importance', table_name='agent_memories')
    op.drop_table('agent_memories')
    # ### end Alembic commands ###
