"""Initial schema

Revision ID: 9301186ee1d5
Revises: 
Create Date: 2026-04-05 18:17:13.736263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9301186ee1d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('parent_community_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index('idx_actions_parent', 'actions', ['parent_community_id'], unique=False)
    op.create_table('closeness_records',
    sa.Column('user_id1', sa.UUID(), nullable=False),
    sa.Column('user_id2', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('last_calculation', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id1', 'user_id2')
    )
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('comment_text', sa.String(length=2000), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_entity', 'comments', ['entity_id', 'entity_type'], unique=False)
    op.create_table('communities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_communities_parent', 'communities', ['parent_id'], unique=False)
    op.create_table('members',
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('seniority', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('community_id', 'user_id')
    )
    op.create_index('idx_members_seniority', 'members', ['community_id', 'seniority'], unique=False)
    op.create_index('idx_members_user', 'members', ['user_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('proposal_type', sa.String(length=50), nullable=False),
    sa.Column('proposal_status', sa.String(length=20), nullable=False),
    sa.Column('proposal_text', sa.String(length=2000), nullable=True),
    sa.Column('val_uuid', sa.UUID(), nullable=True),
    sa.Column('val_text', sa.String(length=2000), nullable=True),
    sa.Column('pulse_id', sa.UUID(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_proposals_community_status', 'proposals', ['community_id', 'proposal_status'], unique=False)
    op.create_index('idx_proposals_pulse', 'proposals', ['pulse_id'], unique=False)
    op.create_index('idx_proposals_type', 'proposals', ['community_id', 'proposal_type'], unique=False)
    op.create_table('pulse_supports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pulse_id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'pulse_id')
    )
    op.create_index('idx_pulse_supports_pulse', 'pulse_supports', ['pulse_id'], unique=False)
    op.create_index('idx_pulse_supports_user', 'pulse_supports', ['user_id', 'community_id'], unique=False)
    op.create_table('pulses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pulses_community_status', 'pulses', ['community_id', 'status'], unique=False)
    op.create_table('statements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('statement_text', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('prev_statement_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_statements_community', 'statements', ['community_id', 'status'], unique=False)
    op.create_table('supports',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('support_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'proposal_id')
    )
    op.create_index('idx_supports_proposal', 'supports', ['proposal_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('about', sa.String(length=1000), nullable=True),
    sa.Column('wallet_address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('variables',
    sa.Column('community_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('community_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variables')
    op.drop_table('users')
    op.drop_index('idx_supports_proposal', table_name='supports')
    op.drop_table('supports')
    op.drop_index('idx_statements_community', table_name='statements')
    op.drop_table('statements')
    op.drop_index('idx_pulses_community_status', table_name='pulses')
    op.drop_table('pulses')
    op.drop_index('idx_pulse_supports_user', table_name='pulse_supports')
    op.drop_index('idx_pulse_supports_pulse', table_name='pulse_supports')
    op.drop_table('pulse_supports')
    op.drop_index('idx_proposals_type', table_name='proposals')
    op.drop_index('idx_proposals_pulse', table_name='proposals')
    op.drop_index('idx_proposals_community_status', table_name='proposals')
    op.drop_table('proposals')
    op.drop_index('idx_members_user', table_name='members')
    op.drop_index('idx_members_seniority', table_name='members')
    op.drop_table('members')
    op.drop_index('idx_communities_parent', table_name='communities')
    op.drop_table('communities')
    op.drop_index('idx_comments_entity', table_name='comments')
    op.drop_table('comments')
    op.drop_table('closeness_records')
    op.drop_index('idx_actions_parent', table_name='actions')
    op.drop_table('actions')
    # ### end Alembic commands ###
